name: ConversationPlugin
version: '1.0-SNAPSHOT'
main: minecraft.conversationPlugin.ConversationPlugin
api-version: '1.21'
commands:
  conversation:
    description: Manages conversations
    usage: /<command>
